In [ ]:
#Question no-1

In [1]:
import numpy as np

In [ ]:
arr1=np.arange(1,11)

In [ ]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Question no-2

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#Question no-3

In [ ]:
arr2=np.arange(2,21,2)

In [ ]:
arr2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
#Question no-4

In [ ]:
arr1=np.array([1,2,3])

In [ ]:
arr2=np.array([4,5,6])

In [ ]:
arr1+arr2

array([5, 7, 9])

In [ ]:
arr1-arr2

array([-3, -3, -3])

In [ ]:
arr1*arr2

array([ 4, 10, 18])

In [ ]:
arr1/arr2

array([0.25, 0.4 , 0.5 ])

In [ ]:
#Question no-5

In [ ]:
arr6=np.random.randint(100,500,100)

In [ ]:
arr6

array([223, 347, 296, 357, 206, 357, 393, 356, 472, 220, 453, 143, 361,
       190, 410, 135, 137, 328, 110, 373, 122, 240, 345, 406, 201, 359,
       304, 390, 446, 185, 121, 112, 365, 100, 329, 195, 283, 288, 288,
       213, 384, 441, 366, 442, 285, 128, 109, 489, 416, 146, 291, 223,
       474, 324, 362, 488, 265, 130, 453, 359, 101, 197, 286, 422, 450,
       177, 440, 455, 156, 168, 152, 340, 150, 477, 323, 423, 433, 461,
       433, 393, 207, 444, 275, 150, 130, 250, 477, 143, 363, 375, 318,
       104, 242, 348, 401, 331, 426, 298, 180, 297])

In [ ]:
arr6.mean()

299.3

In [ ]:
arr6.sort()

In [ ]:
arr6

array([100, 101, 104, 109, 110, 112, 121, 122, 128, 130, 130, 135, 137,
       143, 143, 146, 150, 150, 152, 156, 168, 177, 180, 185, 190, 195,
       197, 201, 206, 207, 213, 220, 223, 223, 240, 242, 250, 265, 275,
       283, 285, 286, 288, 288, 291, 296, 297, 298, 304, 318, 323, 324,
       328, 329, 331, 340, 345, 347, 348, 356, 357, 357, 359, 359, 361,
       362, 363, 365, 366, 373, 375, 384, 390, 393, 393, 401, 406, 410,
       416, 422, 423, 426, 433, 433, 440, 441, 442, 444, 446, 450, 453,
       453, 455, 461, 472, 474, 477, 477, 488, 489])

In [ ]:
arr7=arr6[49]+arr6[50]

In [ ]:
arr7

641

In [ ]:
arr7/2             #median

320.5

In [ ]:
arr6.std()

117.72803404457242

In [ ]:
#Question no-6

In [26]:
arr8=np.random.randint(10,240,12)

In [27]:
arr8

array([218, 178,  93,  30, 187, 193,  28, 157, 224, 215, 168, 110])

In [28]:
arr8.reshape(3,4)

array([[218, 178,  93,  30],
       [187, 193,  28, 157],
       [224, 215, 168, 110]])

In [ ]:
#Question no-7

In [ ]:
arr=np.square([1,2,3,4,5])

In [ ]:
arr

array([ 1,  4,  9, 16, 25])

In [ ]:
#Question no-8

In [19]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#Question no-9

In [ ]:
a=np.array([1,2,3])

In [ ]:
b=np.array([4,5,6])

In [ ]:
arr=np.dot(a,b)

In [ ]:
arr

32

In [ ]:
#Question no-10

In [29]:
arr8

array([218, 178,  93,  30, 187, 193,  28, 157, 224, 215, 168, 110])

In [30]:
arr8.argmax()

8

In [31]:
arr8.argmin()

6

In [ ]:
#Question no-11

In [ ]:
a=np.zeros((4,3))

In [ ]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
b=np.ones((4,3))

In [ ]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.concatenate((a,b),axis=1)

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [ ]:
np.concatenate([a,b])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#Question no-12

In [ ]:
arr12=np.array([[1,2,3,4,5],[6,7,8,9,0],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]])

In [ ]:
arr12

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9,  0],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr12.sum(0)     #coloum wise

array([52, 57, 62, 67, 62])

In [ ]:
arr12.sum(1)       #row wise

array([ 15,  30,  60,  85, 110])

In [ ]:
#Question no-13

In [ ]:
a=np.arange(20)

In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
b=np.arange(1,25,2)

In [ ]:
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [ ]:
np.intersect1d(a,b)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
#Question no-14

In [ ]:
arr14=np.array([[5,6,-7,8],[-9,-10,11,12],[-13,14,15,16],[-17,18,-19,-20]])

In [ ]:
arr14

array([[  5,   6,  -7,   8],
       [ -9, -10,  11,  12],
       [-13,  14,  15,  16],
       [-17,  18, -19, -20]])

In [ ]:
arr14[arr14<0]=0

In [ ]:
arr14

array([[ 5,  6,  0,  8],
       [ 0,  0, 11, 12],
       [ 0, 14, 15, 16],
       [ 0, 18,  0,  0]])

In [ ]:
#Question no-15

In [ ]:
arr15=np.random.randint(1,100,40)

In [ ]:
arr15

array([84, 11, 60, 68, 90, 55, 14, 44, 24, 71, 14, 89, 72, 38, 57, 12, 19,
       57, 16, 45, 73, 17, 29, 58, 72, 73, 52, 21, 11,  3, 54, 89, 59, 20,
       36,  2,  5, 12,  3, 15])

In [ ]:
arr15.sort()

In [ ]:
arr15

array([ 2,  3,  3,  5, 11, 11, 12, 12, 14, 14, 15, 16, 17, 19, 20, 21, 24,
       29, 36, 38, 44, 45, 52, 54, 55, 57, 57, 58, 59, 60, 68, 71, 72, 72,
       73, 73, 84, 89, 89, 90])

In [ ]:
#Question no-16

In [48]:
a=np.arange(1,13)

In [42]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [49]:
b=np.arange(18,30)

In [44]:
b

array([18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28])

In [50]:
x=np.absolute(a-b)

In [51]:
x

array([17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17])

In [ ]:
#Question no-17

In [53]:
arr17=np.arange(11,31).reshape(5,4)

In [54]:
arr17

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 25, 26],
       [27, 28, 29, 30]])

In [55]:
a=arr17[0]

In [56]:
a

array([11, 12, 13, 14])

In [57]:
b=arr17[:,[-1]]

In [58]:
b

array([[14],
       [18],
       [22],
       [26],
       [30]])

In [ ]:
#Question no-18

In [3]:
a=np.array([1,2,3,4,5,6,7,8,9])


In [5]:
x=a[0:len(a)+1]

In [6]:
print(x)

[1 2 3 4 5 6 7 8 9]


In [7]:
#Question no-19

In [9]:
arr=np.array([[10,1,14,16,18,20],
               [22,24,26,28,30,32],
               [34,36,38,40,42,44],
               [46,48,50,52,54,56],
               [58,60,62,64,66,68],
               [70,72,74,76,78,80]])

In [10]:
arr

array([[10,  1, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78, 80]])

In [12]:
x=arr[2:4,[2,3]]

In [13]:
x

array([[38, 40],
       [50, 52]])

In [14]:
#Question no-20

In [15]:
a=np.array([1,2,3,4,5,6,7,8,9])

In [16]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
x=a[::-1]

In [18]:
x

array([9, 8, 7, 6, 5, 4, 3, 2, 1])